# Generated by Django 5.2.6 on 2025-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('it_actve', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
