# Generated by Django 5.2.6 on 2025-09-15 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='it_actve',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
